import datetime
import json
import os
from dataclasses import dataclass, field
from enum import Enum, IntEnum, auto
from pathlib import Path
from typing import List, Optional, Tuple

CONFIG_RELPATH = "ai-notes/config.json"

# Displaced files go to one timestamped directory per run, the same place and
# scheme install.sh uses, so there is a single obvious place to look. Timestamped
# rather than a fixed `<file>.bak` beside the original: a fixed name collides
# with itself on the next run, which is the only reason the old code had to
# refuse rather than overwrite. install.sh exports its own directory through
# ENV_BACKUP_DIR so one install run collects everything under one timestamp.
BACKUP_DIRNAME = ".dotfiles-backup"

# Every agent is handed the same assembled document, so it is written once to
# this file beside the config and each agent's path is symlinked to it. Copying
# it per agent would leave several files to drift apart, and would put the local
# rules on disk once per agent rather than once.
ASSEMBLED_RELPATH = "ai-notes/rules.md"

# Additive mode appends everything generated inside this one outer pair, so a
# re-run strips the whole region and writes it fresh. Without an outer boundary
# the append would either duplicate on every run or need to guess which of the
# reader's own headings were once ours.
GENERATED_BEGIN = "### BEGIN ai-rules — everything to END ai-rules is regenerated on each run ###"
GENERATED_END   = "### END ai-rules ###"

# How an agent's existing rules file is treated.
RULES_MODE_CLOBBER  = "clobber"
RULES_MODE_ADDITIVE = "additive"
RULES_MODES         = (RULES_MODE_CLOBBER, RULES_MODE_ADDITIVE)

LOCAL_BEGIN    = "### LOCAL (DO NOT TOUCH — auto-generated by `ai-rules apply`) ###"
LOCAL_END      = "### END LOCAL ###"

# Every module gets the same treatment the private layer already got: wrapped in
# a pair of markers naming the file it came from. The assembled document is then
# self-describing — a reader landing in the middle of it can see which source
# file to edit — and the same strip_block() that keeps the LOCAL block from
# nesting keeps these from nesting too.
MODULE_BEGIN_TEMPLATE = "### {name} (DO NOT TOUCH — auto-generated by `ai-rules apply`) ###"
MODULE_END_TEMPLATE   = "### END {name} ###"

# Shareable rule modules. Discovered by globbing this directory rather than
# listed here: dropping in a `something.md` is meant to be the whole of adding a
# module, with no constant, config key or prompt to write by hand.
RULES_DIRNAME = "rules"
RULES_GLOB    = "*.md"

# Each module declares its own metadata on line 1, in an HTML comment so that
# rendered markdown never shows it:
#
#     <!-- ai-rules: order=20, default=on -->
#
# Read by parse_front_matter(). A module with no such line still works — it just
# takes every default, which is "asked about, off unless you say yes".
FRONT_MATTER_PREFIX = "<!-- ai-rules:"
FRONT_MATTER_SUFFIX = "-->"

FRONT_KEY_ORDER     = "order"
FRONT_KEY_DEFAULT   = "default"
FRONT_KEY_PROMPT    = "prompt"
FRONT_FLAG_REQUIRED = "required"

# Where a module with no declared order sorts. Halfway up a 0-99 range, so a
# later module can be placed either side of the ones shipped here without
# renumbering anything.
DEFAULT_MODULE_ORDER = 50

# The daily-notes module, named because one thing genuinely is specific to it:
# `ai-setup` only asks where notes live when this module is switched on. Every
# other module is handled without the tool knowing what it is.
NOTES_MODULE_STEM = "daily-notes"

# The private layer lives beside the config file by default, deliberately NOT
# inside the repo. Cloning a private repo into a tracked directory of this one
# nests two repos, and the placeholder `.gitignore` that ships `ai/local_rules/`
# (`*` plus `!.gitignore`) then lands inside the clone, where it ignores every
# rule file the clone is supposed to hold — so the private repo silently cannot
# track its own rules. Keeping the two trees apart removes the whole class.
LOCAL_RULES_RELPATH = "ai-notes/local_rules"

# The in-repo directory is still read when it is what the config points at, and
# still ships gitignored as a safety net, but nothing defaults to it any more.
LOCAL_RULES_DIRNAME = "local_rules"
LOCAL_RULES_GLOB    = "*.md"


# A README in the local-rules directory documents the directory; it is not a
# rule. Skipped by name because it is markdown like everything else and would
# otherwise be concatenated into the rules verbatim — which is exactly what
# happens when the directory is a repo created through a web UI, since those
# ship a boilerplate README describing how to push to the repo.
LOCAL_RULES_SKIP = ("readme.md",)

# The settings read out of the config file. Named because a mistyped key does
# not fail — config_get quietly hands back the default instead.
CONFIG_KEY_AGENTS             = "agents"
CONFIG_KEY_AI_DIR             = "ai_dir"
CONFIG_KEY_BACKUP_DIR         = "backup_dir"
CONFIG_KEY_LOCAL_RULES_DIR    = "local_rules_dir"
CONFIG_KEY_LOCAL_RULES_REMOTE = "local_rules_remote"
CONFIG_KEY_MODULES            = "modules"
CONFIG_KEY_NOTES_PATH         = "notes_path"
CONFIG_KEY_NOTES_REMOTE       = "notes_remote"
CONFIG_KEY_RULES_MODE         = "rules_mode"
CONFIG_KEY_TARGETS            = "targets"
CONFIG_KEY_UPDATED_AT         = "updated_at"

# Every per-module answer lives under CONFIG_KEY_MODULES, keyed by module stem,
# so adding a module never adds a top-level key. These are the flat keys that
# came before it, each mapped to the stem it now answers for. Read once on load
# and never written, so an older config keeps its answers instead of silently
# reverting to defaults — which here means dropping whole modules of rules.
# Delete this and _module_answers()'s use of it once no such config is left.
CONFIG_KEY_MODULES_WERE = {
    "notes_enabled":     "daily-notes",
    "misc_enabled":      "misc",
    "universal_enabled": "misc",
}

# The starting point for a machine with no config file yet. Named because it is
# also what ai-setup pre-fills its first prompt with.
DEFAULT_AGENTS = ("claude",)

# The environment variables this module honors, for the same reason: a mistyped
# name reads as unset rather than as an error.
ENV_AI_DIR          = "AI_DIR"
ENV_BACKUP_DIR      = "DOTFILES_BACKUP_DIR"
ENV_XDG_CONFIG_HOME = "XDG_CONFIG_HOME"


class ExitStatus(IntEnum):
    """
    Every process exit status the tools built on this library return, by the
    outcome each one stands for.

    An IntEnum because sys.exit() still needs a real int and comparisons still
    work unchanged, while the name is what a reader or a debugger sees. These
    values are the contract with whatever runs those tools, so they are pinned
    and never renumbered. 2 is deliberately absent: argparse produces it for a
    usage error and exits on its own, so nothing here ever returns it.

    An enum has no call signature of its own, so its members are documented in
    place of the Args/Returns/Raises contract a function carries.

    Members:
        OK: the command did what it was asked.
        NO_RULES_FOUND: every selected layer is absent or blank, so there was
            nothing to write.
        NO_KNOWN_AGENTS: not one configured agent name is recognized, so there
            was nowhere to write.
        BAD_AGENTS_SETTING: the `agents` setting is neither a name nor a list of
            names, so it could not be read at all. 5 is absent for the same kind of
            reason as 2: it reported a backup collision that timestamped backup
            directories made impossible.
        CLONE_FAILED: the configured local-rules remote could not be cloned, so
            setup stopped before writing any settings.
        MISSING_MODULE: a selected rules module has no file behind it. Nothing
            was written, because writing would silently drop that module's rules.
        SYNC_CONFLICT: a notes sync hit a real merge conflict. The rebase was
            aborted, so the working tree is exactly as it was, and a person has
            to decide which side wins.
        SYNC_LOCKED: another notes sync is already running against the same
            directory, so this one did nothing rather than interleave git
            commands with it.
        NOT_A_REPO: the notes directory is not a git repository. Nothing was
            created — making a repo out of someone's work is their decision.
    """

    OK                 = 0
    NO_RULES_FOUND     = 1
    NO_KNOWN_AGENTS    = 3
    BAD_AGENTS_SETTING = 4
    CLONE_FAILED       = 6
    MISSING_MODULE     = 7
    SYNC_CONFLICT      = 8
    SYNC_LOCKED        = 9
    NOT_A_REPO         = 10


class RulesRoot(Enum):
    """
    Which directory a supported agent's rules file is resolved against.

    The member values are auto-assigned and mean nothing on their own — they are
    never stored or compared, so a member only ever matches itself. Members are
    documented in place of the Args/Returns/Raises contract, as on ExitStatus
    above.

    Members:
        HOME: the user's home directory, where an agent that reads its rules off
            disk keeps them.
        CONFIG_DIR: the directory holding this tool's config file, where the text
            for an agent that reads no such file is parked instead.
    """

    HOME       = auto()
    CONFIG_DIR = auto()


@dataclass(frozen=True)
class SupportedAgent:
    """
    One agent this tool knows how to write a rules file for.

    Frozen because this describes what the tool supports rather than anything a
    run produces: the same record is read by every apply, so nothing should be
    able to edit it in place.

    Args:
        name (str): the name accepted in the `agents` setting, e.g. "claude".
        root (RulesRoot): which directory `relpath` is resolved against.
        relpath (tuple): (str, ...) the path parts under `root`, e.g.
            (".claude", "CLAUDE.md"). Never empty.
        needs_manual_paste (bool): True when writing the file is only half the
            job — the agent reads its rules out of its own settings UI rather
            than off disk, so the text still has to be pasted in by hand.
            Defaults to False, which is every agent that reads the file itself.

    Returns:
        None

    Raises:
        None
    """

    name:               str
    root:               RulesRoot
    relpath:            Tuple[str, ...]
    needs_manual_paste: bool = False

    def rules_path(self, roots):
        """
        Resolve the rules file this agent reads.

        The directories arrive keyed by RulesRoot rather than as one positional
        parameter each: both are plain paths, so a positional pair could be
        passed the wrong way round and would then resolve every agent under the
        wrong directory without any error to show for it.

        Args:
            roots (dict): {RulesRoot: pathlib.Path} the directory each root
                names. Must carry an entry for this agent's `root`. Callers
                resolve the whole mapping once, so every agent in a run is built
                against the same directories.

        Returns:
            pathlib.Path: `relpath` joined onto the directory `root` names.
            Absolute whenever that directory is. Not guaranteed to exist.

        Raises:
            KeyError: `roots` carries no entry for this agent's `root`.
        """

        return roots[self.root].joinpath(*self.relpath)


# Every agent this tool can write rules for, keyed by the name the `agents`
# setting uses so resolving one is a single lookup. Cursor has no rules file it
# reads on its own, so its text is parked beside the config for pasting in.
SUPPORTED_AGENTS = {
    agent.name: agent
    for agent in (
        SupportedAgent(name="claude", root=RulesRoot.HOME,       relpath=(".claude", "CLAUDE.md")),
        SupportedAgent(name="codex",  root=RulesRoot.HOME,       relpath=(".codex",  "AGENTS.md")),
        SupportedAgent(name="cursor", root=RulesRoot.CONFIG_DIR, relpath=("cursor-user-rules.txt",),
                       needs_manual_paste=True),
    )
}


class NoAgentsError(ValueError):
    """
    Not one configured agent name resolved to a rules file.

    Raised instead of writing nothing and returning quietly, because a run that
    writes zero files is indistinguishable from a successful one at the exit
    status. Callers report it and fail.

    Attributes:
        unknown (list): [str] the configured names that are not in
            SUPPORTED_AGENTS, in config order. Empty when `agents` was itself
            empty.
    """

    def __init__(self, unknown):
        """
        Record the unrecognized names next to the message.

        Args:
            unknown (iterable of str): configured names with no
                SUPPORTED_AGENTS entry.

        Returns:
            None

        Raises:
            None
        """

        self.unknown = list(unknown)

        super().__init__(f"no known agents configured: {', '.join(self.unknown) or '(none)'}")


class BadAgentsError(ValueError):
    """
    The `agents` setting is not an agent name, nor a list of them.

    A hand-edited config can end up holding `"agents": null`, `"agents": 5`, or
    a list with a non-string in it. Each of those reaches the write path and
    surfaces as a TypeError from somewhere deep inside it, so the shape is
    checked up front and reported as the configuration error it is.

    Attributes:
        value: the offending value — the setting itself when it is not a list,
            or the first element of that list which is not a string.
    """

    def __init__(self, value):
        """
        Record the offending value next to the message.

        Args:
            value: the setting, or the list element, that is not an agent name.

        Returns:
            None

        Raises:
            None
        """

        self.value = value

        super().__init__(f"invalid 'agents' setting: expected a name or a list of names, got {value!r}")


class EmptyRulesError(FileNotFoundError):
    """
    Every rules layer came back empty, so there is nothing to assemble.

    Reached when no module is selected and the private layer is absent, or when
    the selected modules exist but hold only whitespace. Assembling that yields
    a document with no rules in it, which would then replace every agent's live
    rules file, so it is refused instead. Subclasses FileNotFoundError because
    callers treat it exactly like missing input: there is nothing to apply.

    Attributes:
        path (pathlib.Path): the rules directory that produced nothing.
    """

    def __init__(self, path):
        """
        Name the empty file and say that nothing was written.

        Args:
            path (str or pathlib.Path): the rules directory that produced no
                text, or produced only whitespace.

        Returns:
            None

        Raises:
            None
        """

        self.path = Path(path)

        super().__init__(f"no rules selected or found, nothing was written: {self.path}")


class MissingModuleError(FileNotFoundError):
    """
    A selected rules module has no file behind it.

    Selecting a module and finding no file is a broken installation, not a
    preference: the config asked for those rules and they do not exist. Skipping
    it would assemble a document that is silently missing a whole discipline and
    then write that over every agent's live rules — a loss nobody sees, because
    the run still reports success. So the assembly refuses instead.

    Attributes:
        name (str): the module filename that was selected but absent.
        rules_dir (pathlib.Path): the directory that was searched.
    """

    def __init__(self, name, rules_dir):
        """
        Name the missing module, the directory searched, and what to do.

        Args:
            name (str): the selected module's filename, e.g. "daily-notes.md".
            rules_dir (str or pathlib.Path): the rules directory searched for it.

        Returns:
            None

        Raises:
            None
        """

        self.name      = name
        self.rules_dir = Path(rules_dir)

        super().__init__(
            f"selected rules module {name!r} is missing from {self.rules_dir}. "
            f"Restore the file, or turn the module off in the config"
        )


@dataclass(frozen=True)
class AgentTarget:
    """
    One agent name resolved to the rules file that agent reads.

    Frozen because the backup and the overwrite that follows it have to name one
    and the same file, and this record is what says which. Fixing it at
    resolution time is how that pairing is settled once rather than being
    something the write path decides for itself.

    Args:
        agent (SupportedAgent): the table entry the configured name resolved to.
            Carried whole rather than by name, so a caller asking what this
            agent needs reads the record SUPPORTED_AGENTS holds instead of a
            copy of one field of it.
        path (pathlib.Path): the rules file that agent reads. Not guaranteed to
            exist.

    Returns:
        None

    Raises:
        None
    """

    agent: SupportedAgent
    path:  Path


@dataclass(frozen=True)
class WrittenRules:
    """
    One agent's rules file as a single apply run left it.

    Args:
        agent (SupportedAgent): the agent whose rules were written. Callers key
            per-agent follow-up messages off its traits — `needs_manual_paste`
            says the write left something for the user to do — rather than off
            its name, so a new agent needing the same follow-up gets it from
            SUPPORTED_AGENTS alone.
        target (pathlib.Path): the rules file that was written.
        backup (pathlib.Path or None): the copy holding what `target` contained
            before the write, or None when `target` did not exist beforehand and
            there was therefore nothing to preserve.

    Returns:
        None

    Raises:
        None
    """

    agent:       str
    target:      Path
    backup:      Optional[Path]
    is_appended: bool = False


@dataclass(frozen=True)
class ResolvedTargets:
    """
    What agent_targets() made of a list of configured agent names.

    Args:
        targets (list): [AgentTarget] one entry per recognized name, in the
            order given. May be empty.
        unknown (list): [str] the names with no SUPPORTED_AGENTS entry, in the
            order given. May be empty.

    Returns:
        None

    Raises:
        None
    """

    targets: List[AgentTarget]
    unknown: List[str]


@dataclass(frozen=True)
class ApplyResult:
    """
    What one apply_rules() run wrote, and which names it could not place.

    Args:
        written (list): [WrittenRules] one entry per rules file written, in
            config order. Never empty — apply_rules raises NoAgentsError rather
            than returning to say it wrote nothing.
        unknown (list): [str] configured names with no SUPPORTED_AGENTS entry,
            skipped rather than written. The caller is expected to report them.
            May be empty.
        assembled (pathlib.Path): the one file holding the assembled rules, which
            every entry in `written` now points at. Reported because it, not the
            agent paths, is the file to open to see what was applied.

    Returns:
        None

    Raises:
        None
    """

    written:   List[WrittenRules]
    unknown:   List[str]
    assembled: Path


def config_path():
    """
    Locate the machine-local config file.

    Honors $XDG_CONFIG_HOME, falling back to ~/.config. Does not create the
    file or its parent directory, and does not check that either exists.

    Args:
        None

    Returns:
        pathlib.Path: absolute path to the config file.

    Raises:
        None
    """

    # An empty XDG_CONFIG_HOME counts as unset, same as the XDG spec says
    base = os.environ.get(ENV_XDG_CONFIG_HOME)
    root = Path(base) if base else Path(os.path.expanduser("~")) / ".config"

    return root / CONFIG_RELPATH


def default_local_rules_dir():
    """
    Where the private rules layer lives when the config does not say.

    Args:
        None

    Returns:
        pathlib.Path: `<config dir>/ai-notes/local_rules`, beside the config
        file and the assembled rules. Not guaranteed to exist.

    Raises:
        None
    """

    return config_path().parent.parent / LOCAL_RULES_RELPATH


def assembled_path():
    """
    Locate the one assembled rules file every agent's path points at.

    Resolved against the same directory as the config file, so it lands in this
    tool's own space rather than in any agent's, and inherits $XDG_CONFIG_HOME.

    Args:
        None

    Returns:
        pathlib.Path: absolute path to the assembled rules file. Not guaranteed
        to exist — `ai-rules apply` is what creates it.

    Raises:
        None
    """

    return config_path().parent.parent / ASSEMBLED_RELPATH


def links_to(path, destination):
    """
    Say whether a path is a symlink already pointing at a given file.

    Compared after resolving both sides, so a link written through a symlinked
    home directory still recognizes its own destination.

    Args:
        path (pathlib.Path): the path to inspect. Need not exist.
        destination (pathlib.Path): the file `path` would have to point at.

    Returns:
        bool: True only when `path` is a symlink resolving to `destination`.
        False when it is a regular file, a directory, absent, or a symlink
        aimed somewhere else — including a dangling one.

    Raises:
        None
    """

    if not path.is_symlink():
        return False

    # strict=False: a dangling link resolves to the missing path rather than
    # raising, and then simply fails to match.
    return path.resolve() == destination.resolve()


def config_read():
    """
    Read the whole config file.

    Args:
        None

    Returns:
        dict: every setting in the file, or {} if the file does not exist.

    Raises:
        OSError: the file exists but cannot be read.
        ValueError: the file is not valid JSON.
    """

    path = config_path()
    if not path.is_file():
        return {}

    return json.loads(path.read_text(encoding="utf-8"))


def config_get(key, default=""):
    """
    Read one setting from the config file.

    Args:
        key (str): setting name to look up.
        default: returned when the key, or the config file itself, is absent.

    Returns:
        The stored value, with its JSON type preserved (str, bool, int, list,
        dict), or `default`.

    Raises:
        OSError: the config file exists but cannot be read.
        ValueError: the config file is not valid JSON.
    """

    return config_read().get(key, default)


def _atomic_write(path, text):
    """
    Replace a file's contents in one step, creating its parent if needed.

    The text goes to a scratch file beside the target and is swapped in with
    os.replace, so a reader never sees a half-written file and an interrupted
    write leaves the previous contents intact. Every file this module writes —
    the config and each agent's rules file — goes through here. The scratch file
    is a sibling of the target, so the two share a filesystem and the swap is
    atomic.

    Args:
        path (str or pathlib.Path): file to write. Its parent directory is
            created when absent; the file itself need not already exist.
        text (str): the full contents to write, encoded as UTF-8.

    Returns:
        None

    Raises:
        OSError: the parent directory cannot be created, or the write or the
            replace fails (e.g. permissions, read-only filesystem, no space).
            The target keeps whatever it held before the call.
    """

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)

    # The pid keeps concurrent writers off each other's scratch file
    tmp = target.with_name(f"{target.name}.{os.getpid()}.tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(str(tmp), str(target))
    finally:
        try:
            tmp.unlink()
        except OSError:
            # Already gone whenever the replace succeeded, since that moved it.
            # Swallowed so a cleanup failure cannot replace the write's
            # exception with its own and hide why the write actually failed.
            pass


def _config_write(data):
    """
    Serialize the whole config mapping and swap it into place.

    The single place this file's on-disk shape is decided — indentation, key
    order, the trailing newline. Private because `Config.save` is meant to be
    the only way a shipped tool writes this file: a second public writer is how
    `updated_at`, which claims to say when the config was last saved, ends up
    stale after someone changes a setting without going through the record.

    Args:
        data (dict): every setting to write. Replaces the file's contents
            entirely rather than merging, so callers pass the full mapping.

    Returns:
        None

    Raises:
        OSError: the file or its directory cannot be written.
        TypeError: a value is not JSON-serializable.
    """

    # Top-level keys sorted here rather than by sort_keys, which would sort every
    # nested dict too — and the per-module answers are stored in the order their
    # questions were asked, which is information worth keeping. Sorting the top
    # level still means an unrelated edit produces a one-line diff rather than
    # reordering the file; the trailing newline keeps it a well-formed text file.
    ordered = {key: data[key] for key in sorted(data)}
    text    = json.dumps(ordered, indent=2, sort_keys=False) + "\n"

    _atomic_write(config_path(), text)


@dataclass
class Config:
    """
    Every setting this system reads, as one record instead of loose keys.

    Load it once and read attributes off it. `config_get` remains for a one-off
    single key, but anything wanting more than one value should come through
    here: it reads the file once rather than per key, and a misspelled attribute
    is an AttributeError rather than a silently returned default — which is the
    specific way a stringly-keyed config goes wrong.

    Mutable on purpose. Reading, editing a field, and saving is the whole
    working shape of `ai-setup`, and a frozen record would force a rebuild of
    all seven fields to change one.

    Args:
        agents (list of str): agent names to write rules for, already normalized
            from the string-or-list the file may hold.
        ai_dir (pathlib.Path or None): the `ai/` directory rules are read from.
            None when never recorded.
        backup_dir (pathlib.Path or None): the root that displaced files are
            filed under, one timestamped directory per run. None means the
            BACKUP_DIRNAME default in the home directory.
        local_rules_dir (pathlib.Path or None): directory holding the private
            `*.md` rules. None when unset; callers supply their own default,
            since it depends on where `ai/` is.
        local_rules_remote (str): git remote the private rules come from, or ""
            when there is none.
        modules (dict): {str: bool} one stored answer per module stem, in the
            order the questions were asked. A stem missing from here has never
            been asked about, and falls back to what that module declares in its
            own front matter — which is what lets a module added to the repo
            take effect without anyone editing a config first.
        notes_path (pathlib.Path or None): where the daily-notes repo lives.
        rules_mode (str): what to do with an agent's existing rules file.
            "clobber" replaces it with a link to the assembled rules, so the
            agent reads this repo's rules and nothing else. "additive" leaves
            the file in place and appends the generated sections to it, so the
            reader keeps their own rules and gains these. Defaults to clobber,
            which is right when there is no file to preserve.
        targets (dict): {str: bool} one stored answer per install.sh target —
            "tmux", "vim", "bash", "ai". A target missing from here has never
            been answered, and install.sh asks. Kept beside the rest so a
            re-run pre-fills rather than asking cold, the same way the rule
            modules do.
        notes_remote (str): git remote the notes repo syncs with, or "" when
            there is none — in which case notes stay local to this machine and
            nothing syncs them anywhere.
        updated_at (str): when this config was last saved, UTC ISO-8601. Set by
            save(); never written by hand.
        extra (dict): any key in the file this class does not know about, kept
            so an older tool cannot silently drop a newer tool's settings when
            it saves.

    Returns:
        None

    Raises:
        None
    """

    agents:             List[str]
    ai_dir:             Optional[Path] = None
    backup_dir:         Optional[Path] = None
    local_rules_dir:    Optional[Path] = None
    local_rules_remote: str            = ""
    modules:            dict           = field(default_factory=dict)
    notes_path:         Optional[Path] = None
    notes_remote:       str            = ""
    rules_mode:         str            = RULES_MODE_CLOBBER
    targets:            dict           = field(default_factory=dict)
    updated_at:         str            = ""
    extra:              dict           = field(default_factory=dict)

    # The keys this class owns. Everything else in the file lands in `extra`,
    # and listing them once is what keeps load() and save() from disagreeing.
    OWNED_KEYS = (
        CONFIG_KEY_AGENTS,
        CONFIG_KEY_AI_DIR,
        CONFIG_KEY_BACKUP_DIR,
        CONFIG_KEY_LOCAL_RULES_DIR,
        CONFIG_KEY_LOCAL_RULES_REMOTE,
        CONFIG_KEY_MODULES,
        CONFIG_KEY_NOTES_PATH,
        CONFIG_KEY_NOTES_REMOTE,
        CONFIG_KEY_RULES_MODE,
        CONFIG_KEY_TARGETS,
        CONFIG_KEY_UPDATED_AT,

        # The superseded flat keys are owned too, so they are left out of
        # `extra` and therefore dropped by the next save. Left in `extra` they
        # would be copied forward forever, and a config holding two keys for one
        # setting is a question about which one wins.
        *CONFIG_KEY_MODULES_WERE,
    )

    @classmethod
    def load(cls):
        """
        Read the whole config file into one record.

        Args:
            None

        Returns:
            Config: the settings on disk. Every field carries its documented
            default where the file says nothing, so a missing file yields a
            usable record rather than an error.

        Raises:
            BadAgentsError: the `agents` setting is neither a name nor a list of
                names.
            OSError: the config file exists but cannot be read.
            ValueError: the config file is not valid JSON.
        """

        data = config_read()

        # Every fallback below is read off this rather than repeated as a
        # literal. Two copies of a default drift, and a drifted one is invisible:
        # it only shows on a machine with no config file, which is the one case
        # nobody re-tests.
        defaults = cls(agents=list(DEFAULT_AGENTS))

        return cls(
            agents             = _agent_names(data.get(CONFIG_KEY_AGENTS, defaults.agents)),
            ai_dir             = _as_path(data.get(CONFIG_KEY_AI_DIR)),
            backup_dir         = _as_path(data.get(CONFIG_KEY_BACKUP_DIR)),
            local_rules_dir    = _as_path(data.get(CONFIG_KEY_LOCAL_RULES_DIR)),
            local_rules_remote = data.get(CONFIG_KEY_LOCAL_RULES_REMOTE, defaults.local_rules_remote),
            modules            = _module_answers(data),
            notes_path         = _as_path(data.get(CONFIG_KEY_NOTES_PATH)),
            notes_remote       = data.get(CONFIG_KEY_NOTES_REMOTE, defaults.notes_remote),
            rules_mode         = _rules_mode(data.get(CONFIG_KEY_RULES_MODE), defaults.rules_mode),
            targets            = _bool_map(data.get(CONFIG_KEY_TARGETS)),
            updated_at         = data.get(CONFIG_KEY_UPDATED_AT, defaults.updated_at),
            extra              = {k: v for k, v in data.items() if k not in cls.OWNED_KEYS},
        )

    def save(self):
        """
        Write every field back to the config file, stamping the save time.

        Args:
            None

        Returns:
            None

        Raises:
            OSError: the config file or its directory cannot be written.
            TypeError: a value in `extra` is not JSON-serializable.
        """

        # UTC and second-resolution, so the stamp sorts and compares the same on
        # every machine. timezone.utc rather than utcnow(), which is deprecated
        # and hands back a naive datetime that reads as local time.
        self.updated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        data = dict(self.extra)
        data.update({
            CONFIG_KEY_AGENTS:             list(self.agents),
            CONFIG_KEY_LOCAL_RULES_REMOTE: self.local_rules_remote,
            CONFIG_KEY_MODULES:            dict(self.modules),
            CONFIG_KEY_NOTES_REMOTE:       self.notes_remote,
            CONFIG_KEY_RULES_MODE:         self.rules_mode,
            CONFIG_KEY_TARGETS:            dict(self.targets),
            CONFIG_KEY_UPDATED_AT:         self.updated_at,
        })

        # Paths go out as strings, and an unset one is left out entirely rather
        # than written as null, so absent and "explicitly nothing" stay distinct.
        for key, value in ((CONFIG_KEY_AI_DIR,          self.ai_dir),
                           (CONFIG_KEY_BACKUP_DIR,      self.backup_dir),
                           (CONFIG_KEY_LOCAL_RULES_DIR, self.local_rules_dir),
                           (CONFIG_KEY_NOTES_PATH,      self.notes_path)):
            if value is not None:
                data[key] = str(value)

        _config_write(data)

    def describe(self):
        """
        Render the settings as aligned label/value lines for a caller to print.

        Returns lines rather than printing them, so this module stays free of
        stdout and each CLI puts its own tag in front.

        Args:
            None

        Returns:
            list: [str] one "label: value" line per setting, in a fixed order,
            with the values aligned in a column. Never empty.

        Raises:
            None
        """

        rows = [
            ("rules source",       self.ai_dir),
            ("agents",             " ".join(self.agents)),
            ("local rules dir",    self.local_rules_dir),
            ("backup dir",         self.backup_dir or default_backup_root()),
            ("local rules remote", self.local_rules_remote),
            ("notes path",         self.notes_path),
            ("notes remote",       self.notes_remote),
            ("rules mode",         self.rules_mode),
        ]

        # One row per answered module, in config order, so what gets printed
        # grows with the directory instead of with a hand-maintained list here.
        rows.extend((f"target {name}", is_wanted) for name, is_wanted in self.targets.items())
        rows.extend((f"module {stem}", is_enabled) for stem, is_enabled in self.modules.items())

        rows.append(("config file", config_path()))
        width = max(len(label) for label, _ in rows)

        return [f"{label + ':':<{width + 1}} {value if value not in (None, '') else '(none)'}"
                for label, value in rows]


def _as_path(value):
    """
    Turn a config value into a Path, leaving an absent one absent.

    Args:
        value (str or None): the stored setting.

    Returns:
        pathlib.Path or None: the path, or None when `value` is None or an empty
        string — an empty path would silently resolve to the current directory.

    Raises:
        TypeError: `value` is neither a string nor None.
    """

    return Path(value) if value else None


def _rules_mode(value, fallback):
    """
    Coerce a stored rules mode into one this tool understands.

    Args:
        value: whatever was in the config file. Anything unrecognised falls
            back rather than raising — a typo here would otherwise stop every
            agent being written, and the safe reading of an unknown mode is the
            documented default.
        fallback (str): the mode to use when `value` is not one of RULES_MODES.

    Returns:
        str: one of RULES_MODES.

    Raises:
        None
    """

    return value if value in RULES_MODES else fallback


def _bool_map(value):
    """
    Coerce a config value into a {str: bool} mapping, or nothing.

    Args:
        value: whatever was in the config file under the key. Anything that is
            not a mapping is discarded rather than raising, on the same grounds
            as an unreadable module `order`: one malformed setting should not
            stop an install or an assembly.

    Returns:
        dict: {str: bool} in the file's order. Empty when `value` is not a
        mapping.

    Raises:
        None
    """

    if not isinstance(value, dict):
        return {}

    return {str(key): bool(entry) for key, entry in value.items()}


def _module_answers(data):
    """
    Pull the per-module answers out of raw config data, old shapes included.

    Args:
        data (dict): the parsed config file. A value under CONFIG_KEY_MODULES
            that is not a mapping is ignored rather than raising, on the same
            grounds as a bad `order`: one malformed setting should not stop
            every agent being written.

    Returns:
        dict: {str: bool} answer per module stem, in config order. Empty when
        nothing has been answered, which means every module falls back to what
        it declares for itself.

    Raises:
        None
    """

    answers = {}

    # Migrated first so the current shape below can override them. Iterating in
    # CONFIG_KEY_MODULES_WERE order with setdefault makes the newer of two keys
    # for one module win, since it is listed first — a config carrying both
    # `misc_enabled` and the older `universal_enabled` is decided by the former.
    for old_key, stem in CONFIG_KEY_MODULES_WERE.items():
        if old_key in data:
            answers.setdefault(stem, bool(data[old_key]))

    answers.update(_bool_map(data.get(CONFIG_KEY_MODULES)))

    return answers


def _agent_names(names):
    """
    Normalize the `agents` setting into a list of names.

    Args:
        names (str or list): the setting as the file stored it. A bare string is
            one name, or several separated by whitespace.

    Returns:
        list: [str] the names, in the order given.

    Raises:
        BadAgentsError: `names` is not a string or a list, or a list holds a
            non-string. Both reach the write path as a bare TypeError from deep
            inside it otherwise.
    """

    # A bare string is one agent name, or several separated by whitespace
    if isinstance(names, str):
        return names.split()

    # null, a number, or an object here would reach list() and raise a bare
    # TypeError from the middle of the write path; a JSON list is the only other
    # shape this setting can legitimately take.
    if not isinstance(names, (list, tuple)):
        raise BadAgentsError(names)

    for name in names:
        # A non-string element survives the SUPPORTED_AGENTS lookup as "unknown"
        # and only blows up later, when the names are joined into a message
        if not isinstance(name, str):
            raise BadAgentsError(name)

    return list(names)


def _line_marker_index(text, marker, start=0, should_use_last=False):
    """
    Find a marker that sits alone on its own line.

    The generated markers always occupy a whole line, so requiring that keeps a
    marker quoted inside prose or a code fence from being mistaken for one.

    Args:
        text (str): text to search.
        marker (str): the exact marker string, without surrounding newlines.
        start (int): index in `text` to start searching from.
        should_use_last (bool): True returns the last qualifying occurrence, False the
            first.

    Returns:
        int: index in `text` where the marker begins, or -1 when no occurrence
        at or after `start` has a line to itself.

    Raises:
        None
    """

    found = -1
    at    = text.find(marker, start)

    while at != -1:
        # A marker owns its line when only a line break (or the edge of the
        # text) sits on either side of it.
        opens  = at == 0 or text[at - 1] == "\n"
        closes = text[at + len(marker):at + len(marker) + 1] in ("", "\n")

        if opens and closes:
            found = at
            if not should_use_last:
                return found

        at = text.find(marker, at + 1)

    return found


def strip_block(text, begin, end, should_repeat=False, should_use_last_end=False):
    """
    Remove a marker-delimited region from the rules text, markers included.

    Only markers alone on their own line count, so a marker quoted inside prose
    or a code fence is left alone. Stripping the generated LOCAL region is what
    makes re-assembly idempotent: the stale block is taken out before a fresh
    one is appended, so it is replaced rather than duplicated.

    Args:
        text (str): rules text that may hold zero or more `begin`...`end`
            regions.
        begin (str): the exact opening marker, without surrounding newlines.
        end (str): the exact closing marker, without surrounding newlines.
        should_repeat (bool): True removes every region, False at most one. Use True
            when the region can legitimately occur more than once.
        should_use_last_end (bool): True closes a region on the LAST whole-line `end`
            marker after its begin marker, False on the FIRST. Use True only
            when there is a single region whose end marker is the document's
            last line.

    Returns:
        str: `text` with the matching region(s) removed, returned unchanged when
        no whole-line begin marker is present. A begin marker with no whole-line
        end marker after it takes everything from the marker to the end of the
        text with it.

    Raises:
        None
    """

    out   = text
    start = _line_marker_index(out, begin)

    while start != -1:
        # FIRST end marker keeps repeated regions from merging (the prose between
        # them would be swallowed); LAST protects a single generated block whose
        # body may quote the end marker on a line of its own.
        stop = _line_marker_index(out, end, start + len(begin), should_use_last=should_use_last_end)

        if stop == -1:
            cut = len(out)
        else:
            # Step past the marker, then past its own line break so the cut lands
            # on a line boundary. The newline in FRONT of the begin marker is left
            # in place, so a blank line can remain where the region was.
            cut = stop + len(end)
            if out[cut:cut + 1] == "\n":
                cut += 1

        out = out[:start] + out[cut:]

        if not should_repeat:
            break

        start = _line_marker_index(out, begin)

    return out


def parse_front_matter(text):
    """
    Read a module's self-declared metadata off its first line.

    The line is an HTML comment so a rendered view never shows it:

        <!-- ai-rules: order=20, default=on, prompt="Include the notes rules" -->

    Entries are comma-separated. `key=value` sets a value; a bare word sets a
    flag to True. A value may be quoted, which is how a prompt containing a
    comma survives the split.

    Args:
        text (str): the module's full contents. A file whose first line is not
            such a comment simply declares nothing.

    Returns:
        dict: {str: str or bool} the declared entries, lowercased keys. Empty
        when the file declares nothing, which is not an error.

    Raises:
        None
    """

    first = text.lstrip().split("\n", 1)[0].strip()

    if not (first.startswith(FRONT_MATTER_PREFIX) and first.endswith(FRONT_MATTER_SUFFIX)):
        return {}

    inner   = first[len(FRONT_MATTER_PREFIX):-len(FRONT_MATTER_SUFFIX)]
    entries = {}

    for part in _split_outside_quotes(inner, ","):
        part = part.strip()
        if not part:
            continue

        # maxsplit=1 so a value may itself contain "=" without being re-split
        key, sep, value = part.partition("=")
        key = key.strip().lower()

        # A bare word is a flag. Writing `required` rather than `required=true`
        # is the whole reason to accept both shapes.
        entries[key] = value.strip().strip('"\'') if sep else True

    return entries


def _split_outside_quotes(text, separator):
    """
    Split on a separator, ignoring any that sits inside double quotes.

    Args:
        text (str): the text to split.
        separator (str): a single character to split on.

    Returns:
        list: [str] the pieces, separators removed. Never empty; splitting ""
        yields [""].

    Raises:
        None
    """

    pieces      = [""]
    is_in_quote = False

    for char in text:
        if char == '"':
            is_in_quote = not is_in_quote

        # The separator only separates out here; inside quotes it is content,
        # which is what lets a declared prompt contain a comma.
        if char == separator and not is_in_quote:
            pieces.append("")
            continue

        pieces[-1] += char

    return pieces


def module_title(text, fallback):
    """
    Take a module's human-readable name from its first markdown heading.

    Args:
        text (str): the module's full contents.
        fallback (str): returned when the file has no `# ` heading, so that a
            caller always has something to put in a prompt.

    Returns:
        str: the first level-one heading with its "# " removed, or `fallback`.

    Raises:
        None
    """

    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()

    return fallback


@dataclass(frozen=True)
class RuleModule:
    """
    One shareable rules module, and everything this tool knows about it.

    Frozen because it describes a file on disk as it was read: a run that wants
    different settings re-reads the directory rather than editing these.

    Every field but `path` comes from the module's own front matter or from its
    filename, which is what makes adding a module a matter of adding a file.

    Args:
        path (pathlib.Path): the module file.
        stem (str): filename without ".md". Doubles as the key its answer is
            stored under in the config, so it is what a user sees there.
        title (str): the first markdown heading, used in the setup prompt.
        order (int): sort position, for assembly and for the order questions are
            asked. Ties break on `stem`, so the order is always total.
        is_required (bool): True when the module has no switch and is always
            included. Never asked about.
        declared_default (bool or None): what the module declared for itself,
            or None when it declared nothing. Tri-state on purpose: the private
            layer includes everything by default, so "said off" has to be
            distinguishable from "said nothing", or a private file declaring
            `default=off` would be silently included anyway.
        prompt (str): the question setup asks. Built from `title` when the
            module does not declare one.

    Returns:
        None

    Raises:
        None
    """

    path:             Path
    stem:             str
    title:            str
    order:            int  = DEFAULT_MODULE_ORDER
    is_required:      bool = False
    declared_default: Optional[bool] = None
    prompt:           str  = ""

    @property
    def is_on_by_default(self):
        """
        Whether a shareable module applies before anyone has been asked.

        Args:
            None

        Returns:
            bool: True only when the module declared `default=on`. Declaring
            nothing means off, which is the safe answer for a module someone
            has inherited rather than chosen.

        Raises:
            None
        """

        return self.declared_default is True

    @property
    def filename(self):
        """
        The module's filename, which is what the section markers name.

        Args:
            None

        Returns:
            str: e.g. "daily-notes.md".

        Raises:
            None
        """

        return self.path.name

    def is_selected(self, answers):
        """
        Decide whether this module belongs in the assembly.

        Args:
            answers (dict): {str: bool} the config's stored answer per module
                stem. A stem it has never seen falls back to the module's own
                declared default, so a module added to the repo takes effect
                without anyone editing a config first.

        Returns:
            bool: True when the module should be assembled.

        Raises:
            None
        """

        if self.is_required:
            return True

        return bool(answers.get(self.stem, self.is_on_by_default))


def module_from_file(path):
    """
    Build a RuleModule by reading one module file.

    Args:
        path (str or pathlib.Path): the module file. Must exist and be readable.

    Returns:
        RuleModule: the module as it declares itself.

    Raises:
        OSError: the file cannot be read.
        UnicodeDecodeError: the file is not valid UTF-8.
    """

    path  = Path(path)
    text  = path.read_text(encoding="utf-8")
    front = parse_front_matter(text)
    stem  = path.stem
    title = module_title(text, stem)

    # An unreadable or absent order must not reorder the whole directory, so a
    # bad value falls back rather than raising: a module is rules, not config,
    # and one typo in a comment should not stop every agent being written.
    try:
        order = int(front.get(FRONT_KEY_ORDER, DEFAULT_MODULE_ORDER))
    except (TypeError, ValueError):
        order = DEFAULT_MODULE_ORDER

    return RuleModule(
        path             = path,
        stem             = stem,
        title            = title,
        order            = order,
        is_required      = bool(front.get(FRONT_FLAG_REQUIRED, False)),
        declared_default = _declared_default(front),
        prompt           = front.get(FRONT_KEY_PROMPT) or f"Include the {title} rules",
    )


def _declared_default(front):
    """
    Read a module's declared default, keeping "not declared" distinct from "off".

    Args:
        front (dict): the parsed front matter.

    Returns:
        bool or None: True or False when the module declared one, None when it
        said nothing about it.

    Raises:
        None
    """

    if FRONT_KEY_DEFAULT not in front:
        return None

    return str(front[FRONT_KEY_DEFAULT]).lower() in ("on", "true", "yes", "1")


def discover_modules(rules_dir):
    """
    Find every shareable rules module, in the order they should be used.

    Args:
        rules_dir (str or pathlib.Path): the `rules/` directory. Need not exist;
            a missing directory simply holds no modules.

    Returns:
        tuple: (RuleModule, ...) sorted by declared order then filename, so the
        result is stable across machines and filesystems. Empty when there are
        no modules.

    Raises:
        OSError: the directory exists but a module cannot be read.
        UnicodeDecodeError: a module is not valid UTF-8.
    """

    directory = Path(rules_dir)
    if not directory.is_dir():
        return ()

    modules = []

    # Deliberately not sorted here. glob() order is filesystem-dependent, and the
    # single sort below is what makes the result stable — sorting twice would
    # leave the real ordering rule untestable, since a stable sort over already
    # sorted input hides whether the key does the tie-breaking or the input did.
    for path in directory.glob(RULES_GLOB):
        # Same skip as the private layer, and for the same reason: a README in a
        # rules directory documents the directory rather than instructing an
        # agent. Here it is load-bearing rather than defensive, because this
        # directory is globbed now instead of listed.
        if path.name.lower() in LOCAL_RULES_SKIP:
            continue

        modules.append(module_from_file(path))

    # Sorted on the tuple so ties break on a stable key rather than on whatever
    # order the filesystem handed back
    return tuple(sorted(modules, key=lambda m: (m.order, m.stem)))


def wrap_module(name, body):
    """
    Put one module's text inside markers naming the file it came from.

    Args:
        name (str): the module's filename, e.g. "daily-notes.md".
        body (str): the module's contents, front matter already removed.

    Returns:
        str: the wrapped section, ending in exactly one newline. "" when the
        body is blank — markers around nothing are not rules, and emitting them
        would leave the assembly non-empty and so defeat the check that refuses
        to replace live rules with a document holding none.

    Raises:
        None
    """

    if not body.strip():
        return ""

    begin = MODULE_BEGIN_TEMPLATE.format(name=name)
    end   = MODULE_END_TEMPLATE.format(name=name)

    # One blank line inside each marker, matching the LOCAL block exactly, so
    # every generated section in the assembled file looks the same.
    return f"{begin}\n\n{body.strip(chr(10))}\n\n{end}\n"


def strip_front_matter(text):
    """
    Remove a module's declaration line, which is metadata rather than a rule.

    Args:
        text (str): the module's full contents.

    Returns:
        str: the contents with the leading declaration and the blank line after
        it removed. Unchanged when there is no declaration.

    Raises:
        None
    """

    if not parse_front_matter(text):
        return text

    _, _, rest = text.lstrip().partition("\n")

    return rest.lstrip("\n")


def read_modules(modules):
    """
    Read and wrap the given modules, in the order given.

    Args:
        modules (iterable of RuleModule): the modules to include. Each one's
            file must still exist; see Raises.

    Returns:
        str: the wrapped sections separated by a blank line, or "" when
        `modules` is empty.

    Raises:
        MissingModuleError: a module's file is no longer there.
        OSError: a module exists but cannot be read.
        UnicodeDecodeError: a module is not valid UTF-8.
    """

    parts = []

    for module in modules:
        # Discovery read this file a moment ago, so absence here means it went
        # away mid-run — or that a caller built the record by hand. Either way
        # the config asked for these rules, so refusing beats assembling a
        # document that is quietly short a whole discipline.
        if not module.path.is_file():
            raise MissingModuleError(module.filename, module.path.parent)

        body = strip_front_matter(module.path.read_text(encoding="utf-8"))
        parts.append(wrap_module(module.filename, body))

    return "\n".join(parts)


def missing_modules(modules, answers):
    """
    Find modules the config switched on that are no longer on disk.

    Globbing the directory means a deleted module is simply not discovered, so
    absence would otherwise be invisible — the very silent skip that discovery
    is not allowed to reintroduce. The config is what declares intent: a stem
    answered "yes" is a module someone asked for, so its file going away is a
    broken install rather than a preference.

    Args:
        modules (iterable of RuleModule): every module found on disk.
        answers (dict): {str: bool} stored answer per module stem.

    Returns:
        list: [str] the stems answered "yes" with no module behind them, sorted
        so the report is stable. Empty when nothing is missing.

    Raises:
        None
    """

    present = {module.stem for module in modules}

    return sorted(stem for stem, is_enabled in answers.items() if is_enabled and stem not in present)


def selected_modules(modules, answers):
    """
    Narrow discovered modules to the ones a config asks for.

    Args:
        modules (iterable of RuleModule): every module found on disk.
        answers (dict): {str: bool} stored answer per module stem. Missing stems
            fall back to each module's declared default.

    Returns:
        list: [RuleModule] the selected modules, in the order given.

    Raises:
        None
    """

    return [module for module in modules if module.is_selected(answers)]


def optional_modules(modules):
    """
    Narrow discovered modules to the ones worth asking a question about.

    Args:
        modules (iterable of RuleModule): every module found on disk.

    Returns:
        list: [RuleModule] the modules that carry a switch, in the order given.
        A required module is left out: asking a question whose only valid answer
        is yes trains someone to stop reading the questions that matter.

    Raises:
        None
    """

    return [module for module in modules if not module.is_required]


def local_rules_modules(local_dir):
    """
    Discover the private layer's files, dropping any that are shelved.

    The private layer is read exactly like `ai/rules/`: same glob, same README
    skip, same declaration line, same ordering. It differs in one way, and only
    one — nothing here is asked about. A file in this directory is private and
    machine-local, put there deliberately, so it applies unless it says
    otherwise. `default=off` is therefore how a private rule is shelved without
    deleting it; every other declared entry that only makes sense for a module
    someone opts into (`required`, `prompt`) is simply unused here.

    Args:
        local_dir (str or pathlib.Path): the private rules directory. Need not
            exist; a missing directory simply holds no rules.

    Returns:
        list: [RuleModule] the files that apply, in declared order then
        filename. Empty when the directory is absent or holds nothing.

    Raises:
        OSError: the directory exists but a file cannot be read.
        UnicodeDecodeError: a file is not valid UTF-8.
    """

    # `is not False` rather than a truth test: a file that declared nothing has
    # None here and must be included, which is the opposite of what a shareable
    # module does with the same value.
    return [m for m in discover_modules(local_dir) if m.declared_default is not False]


def read_local_rules(local_dir):
    """
    Concatenate the private local rules into a single block of text.

    Args:
        local_dir (str or pathlib.Path): the private rules directory. Need not
            exist.

    Returns:
        str: each file wrapped in markers naming it, in declared order then
        filename, separated by a blank line. "" when there is nothing to read.

    Raises:
        MissingModuleError: a file vanished between being discovered and read.
        OSError: the directory exists but one of its files cannot be read.
        UnicodeDecodeError: one of the files is not valid UTF-8.
    """

    return read_modules(local_rules_modules(local_dir))


def assemble(shared_text, local_text):
    """
    Build the final per-agent rules from the shared modules and the local layer.

    Args:
        shared_text (str): the selected rule modules, already concatenated.
        local_text (str): the private local rules, appended under the LOCAL
            markers. Skipped entirely when empty or only whitespace.

    Returns:
        str: the assembled rules, always ending in exactly one newline. When a
        LOCAL block is written, one blank line sits inside each of its markers.

    Raises:
        None
    """

    # Stripped even though the modules are files this tool owns: a module that
    # quotes a marker on its own line would otherwise open a block that swallows
    # everything after it on the next run.
    body = strip_block(shared_text, LOCAL_BEGIN, LOCAL_END, should_use_last_end=True)
    body = body.rstrip("\n")

    if local_text.strip():
        # Trailing newlines trimmed so the blank line before LOCAL_END is always
        # exactly one, mirroring the blank line after LOCAL_BEGIN. Lifted to its
        # own name because an f-string cannot hold the backslash this needs.
        block = local_text.rstrip("\n")
        body  = f"{body}\n\n{LOCAL_BEGIN}\n\n{block}\n\n{LOCAL_END}"

    return body + "\n"


def ai_dir(script_path=None):
    """
    Locate the repository's `ai/` directory.

    Args:
        script_path (str or pathlib.Path or None): path to a script living in
            `ai/bin/`, normally the caller's `__file__`. Ignored when the
            `AI_DIR` environment variable is set.

    Returns:
        pathlib.Path: the `ai/` directory. Taken verbatim from `AI_DIR` when
        that is set, otherwise `script_path` resolved through any symlinks and
        walked up two levels. Not guaranteed to exist.

    Raises:
        ValueError: `AI_DIR` is unset and no `script_path` was given.
        RuntimeError: `script_path` runs through a symlink loop. Path.resolve()
            is non-strict here, so it returns a path that does not exist rather
            than raising, and swallows the OSErrors readlink can produce (an
            unreadable parent directory, for instance); a loop is the one case
            it does report, and it reports it as RuntimeError, not OSError.
    """

    override = os.environ.get(ENV_AI_DIR)
    if override:
        return Path(override)

    if script_path is None:
        raise ValueError("ai_dir needs script_path when AI_DIR is unset")

    # resolve() first so a symlinked ai-rules on the PATH walks up to the real
    # ai/ directory rather than to wherever the symlink happens to sit.
    return Path(script_path).resolve().parent.parent


def known_agent_names():
    """
    List the agent names this tool knows how to write rules for.

    The single source of these names is SUPPORTED_AGENTS, so a message built
    from this cannot drift as agents are added or removed.

    Args:
        None

    Returns:
        list: [str] every name accepted in the `agents` setting, sorted.

    Raises:
        None
    """

    return sorted(SUPPORTED_AGENTS)


def configured_agents():
    """
    Read the `agents` setting as a list of names.

    A thin wrapper over Config.load().agents, kept because reading only the
    agent names is a common enough need to deserve a name of its own. Anything
    wanting a second setting should load the Config once instead of calling
    this and then reaching for another key.

    Args:
        None

    Returns:
        list: [str] the configured agent names, in config order. A string
        setting is split on whitespace ("claude codex" -> ["claude", "codex"]).
        Defaults to ["claude"] when the setting or the config file is absent.
        Names are NOT checked against SUPPORTED_AGENTS; agent_targets() does
        that.

    Raises:
        BadAgentsError: the setting is neither a string nor a list of strings.
        OSError: the config file exists but cannot be read.
        ValueError: the config file is not valid JSON. BadAgentsError is a
            ValueError too, so catch it first to tell the two apart.
    """

    return Config.load().agents


def agent_targets(names):
    """
    Map agent names to the rules file each one reads.

    Args:
        names (iterable of str): agent names, e.g. ["claude", "codex"]. Pass a
            list, not a bare string — a string iterates character by character.
            configured_agents() reads the setting and normalizes that for you.

    Returns:
        ResolvedTargets: `.targets` holds one AgentTarget per recognized name,
        in the order given; those paths are not guaranteed to exist.
        `.unknown` holds the names with no SUPPORTED_AGENTS entry, in the order
        given. Either list may be empty.

    Raises:
        None
    """

    # Resolved once for the whole run, not per agent: every target below is then
    # built against the same directories, and one lookup names what each is for.
    roots = {
        RulesRoot.HOME:       Path(os.path.expanduser("~")),
        RulesRoot.CONFIG_DIR: config_path().parent,
    }

    targets = []
    unknown = []

    for name in names:
        supported = SUPPORTED_AGENTS.get(name)

        # An unrecognized name is collected rather than raising, so one stale
        # entry in the config cannot stop the other agents from being written.
        # Returning it lets the caller say so instead of skipping in silence.
        if supported is None:
            unknown.append(name)
            continue

        targets.append(AgentTarget(agent=supported, path=supported.rules_path(roots)))

    return ResolvedTargets(targets=targets, unknown=unknown)


def default_backup_root():
    """
    Name the backup root used when nothing has configured one.

    Args:
        None

    Returns:
        pathlib.Path: `~/.dotfiles-backup`, the same root install.sh defaults to,
        so both tools land in one place without either having to be configured.

    Raises:
        None
    """

    return Path(os.path.expanduser("~")) / BACKUP_DIRNAME


def backup_root():
    """
    Resolve the configured backup root.

    Args:
        None

    Returns:
        pathlib.Path: the `backup_dir` setting when one is recorded, otherwise
        default_backup_root(). This is the root, not the per-run directory —
        backup_dir() adds the timestamp.

    Raises:
        BadAgentsError: the `agents` setting is malformed, since reading the
            config parses the whole record.
        OSError: the config file exists but cannot be read.
        ValueError: the config file is not valid JSON.
    """

    return Config.load().backup_dir or default_backup_root()


def backup_dir(now):
    """
    Name the directory this run moves displaced files into.

    Args:
        now (str): timestamp for the directory name, `YYYYmmdd-HHMMSS`. Passed
            in rather than read here so every file in one run lands together,
            even if the run straddles a second boundary.

    Returns:
        pathlib.Path: `$DOTFILES_BACKUP_DIR` verbatim when install.sh exported
        one, so an install collects its own backups and ours in a single
        directory; otherwise the configured root with `now` below it. Not
        created here.

    Raises:
        None
    """

    # install.sh exports the whole per-run directory, timestamp included, so one
    # install collects its own backups and ours together. A standalone run has no
    # such directory and builds its own under the configured root.
    override = os.environ.get(ENV_BACKUP_DIR)
    if override:
        return Path(override)

    return backup_root() / now


def backup_stamp():
    """
    Produce the timestamp used to name a backup directory.

    Args:
        None

    Returns:
        str: local time as `YYYYmmdd-HHMMSS`. Local rather than UTC, and in the
        same format install.sh uses, so the directories from both tools sort
        together and read as the wall-clock time the user ran them.

    Raises:
        None
    """

    return datetime.datetime.now().strftime("%Y%m%d-%H%M%S")


def backup_path(target, into):
    """
    Name where one displaced file is filed inside a backup directory.

    Args:
        target (str or pathlib.Path): the file about to be replaced.
        into (pathlib.Path): the backup directory from backup_dir().

    Returns:
        pathlib.Path: `target`'s path rebuilt under `into` — relative to the
        home directory when it lives there, otherwise with the leading
        separator dropped. Mirroring the path rather than flattening to the
        basename keeps two files with the same name from overwriting each other
        and says where each came from.

    Raises:
        None
    """

    path = Path(target)
    home = Path(os.path.expanduser("~"))

    try:
        relative = path.relative_to(home)
    except ValueError:
        # Outside home, so anchor on the absolute path with the root stripped
        # rather than raising — relative_to has no None to return.
        relative = Path(*path.parts[1:]) if path.is_absolute() else path

    return into / relative


def _back_up(target, assembled, into):
    """
    Preserve a rules file's current contents before it is replaced.

    The copy is what the caller is about to replace, never what it writes, so a
    run that mangles the rules can be undone by hand from the backup.

    A path that is already this tool's own symlink is skipped: it holds nothing
    but a pointer at `assembled`, which the run is rewriting anyway, so there is
    nothing there to lose.

    Args:
        target (str or pathlib.Path): the rules file about to be replaced.
        assembled (pathlib.Path): the assembled rules file agent paths point at.
        into (pathlib.Path): the backup directory from backup_dir().

    Returns:
        pathlib.Path or None: the backup that was written, or None when there
        was nothing worth preserving — the target is absent, or is already our
        own link.

    Raises:
        OSError: `target` cannot be read, or the backup cannot be written (e.g.
            permissions, read-only filesystem, no space). Let this propagate:
            replacing a file whose contents could not be preserved is the data
            loss the backup exists to prevent.
        UnicodeDecodeError: `target` is not valid UTF-8, so its contents cannot
            be copied out. Refused for the same reason.
    """

    path = Path(target)

    # Our own link from an earlier run. Backing it up would save a pointer.
    if links_to(path, assembled):
        return None

    # A first-ever run has nothing to preserve. is_file() follows a symlink, so
    # a foreign link's contents are preserved before this run repoints it.
    if not path.is_file():
        return None

    backup = backup_path(path, into)
    _atomic_write(backup, path.read_text(encoding="utf-8"))

    return backup


def _link_to_assembled(target, assembled):
    """
    Point an agent's path at the assembled rules file, replacing what is there.

    The link is built under a scratch name and moved into place, so the target
    is never briefly missing and a reader either sees the old file or the new
    link. os.replace acts on the link itself rather than following it, which is
    what lets this stand in for a regular file, a foreign symlink, or nothing.

    Args:
        target (pathlib.Path): the agent path to turn into a symlink. Its parent
            is created when absent.
        assembled (pathlib.Path): the file to point at.

    Returns:
        None

    Raises:
        OSError: the parent cannot be created, or the link cannot be made or
            moved into place (e.g. permissions, a filesystem without symlinks).
    """

    target.parent.mkdir(parents=True, exist_ok=True)

    tmp = target.with_name(f"{target.name}.{os.getpid()}.tmp")
    try:
        tmp.symlink_to(assembled)
        os.replace(str(tmp), str(target))
    finally:
        try:
            tmp.unlink()
        except OSError:
            # Gone whenever the replace succeeded, since that moved it. Swallowed
            # so a cleanup failure cannot mask why the link actually failed.
            pass


def wrap_generated(text):
    """
    Put the assembled rules inside the outer marker pair additive mode replaces.

    Args:
        text (str): the assembled rules.

    Returns:
        str: the same text between GENERATED_BEGIN and GENERATED_END, ending in
        exactly one newline.

    Raises:
        None
    """

    return f"{GENERATED_BEGIN}\n\n{text.strip(chr(10))}\n\n{GENERATED_END}\n"


def additive_text(existing, assembled_text):
    """
    Build what an agent file should hold when the reader's own rules stay.

    Args:
        existing (str): what the file holds now, including any region written by
            an earlier run. "" when the file is new.
        assembled_text (str): the assembled rules to append.

    Returns:
        str: the reader's own content, then the generated region. Ends in one
        newline. Running this on its own output is a no-op, which is what makes
        re-applying safe rather than something that grows the file each time.

    Raises:
        None
    """

    # Stripped before appending, so the previous run's region is replaced rather
    # than accumulated. should_use_last_end because the generated text may quote
    # the end marker — the rules describe their own format.
    kept = strip_block(existing, GENERATED_BEGIN, GENERATED_END, should_use_last_end=True)
    kept = kept.rstrip("\n")

    if not kept:
        return wrap_generated(assembled_text)

    return f"{kept}\n\n{wrap_generated(assembled_text)}"


def _append_to_target(target, assembled_text):
    """
    Write an agent file that keeps the reader's rules and adds the generated ones.

    Args:
        target (pathlib.Path): the agent path. Its parent is created when absent.
            A symlink here — ours from an earlier clobber run — is read for its
            contents but replaced by a real file, since additive mode cannot
            append to a file this tool also owns.
        assembled_text (str): the assembled rules to append.

    Returns:
        None

    Raises:
        OSError: the parent cannot be created, or the file cannot be read or
            written.
        UnicodeDecodeError: the existing file is not valid UTF-8.
    """

    target.parent.mkdir(parents=True, exist_ok=True)

    # A symlink of ours holds the assembled rules and nothing of the reader's,
    # so carrying its contents across would append this repo's rules to a copy
    # of this repo's rules. Switching modes starts the file from nothing.
    existing = ""
    if target.is_file() and not target.is_symlink():
        existing = target.read_text(encoding="utf-8")

    _atomic_write(target, additive_text(existing, assembled_text))


def apply_rules(base_dir):
    """
    Assemble the rules and write them to every configured agent's file.

    Anything at a target path that this tool did not put there is copied into a
    timestamped directory under ~/.dotfiles-backup first, so the contents this
    run replaces survive a bad apply and can be restored by hand. A path that is
    already our own symlink holds a pointer rather than rules, so it is skipped
    and a re-run costs nothing.

    Args:
        base_dir (str or pathlib.Path): the `ai/` directory holding `rules/`
            and, by default, `local_rules/`.

    Returns:
        ApplyResult: `.written` holds one WrittenRules per resolved target, in
        config order; it always holds at least one record, and a record's
        `.backup` is None where that target did not exist yet. `.unknown` holds
        configured names with no SUPPORTED_AGENTS entry, skipped rather than
        written — the caller is expected to report them.

    Raises:
        BadAgentsError: the `agents` setting is neither a name nor a list of
            names. Nothing is written or backed up before this is raised.
        EmptyRulesError: every selected module and the private layer are all
            absent or hold only whitespace, so there is nothing to assemble.
            Nothing is written or backed up before this is raised.
        MissingModuleError: a module the config selected has no file behind it.
            Nothing is written or backed up before this is raised.
        FileNotFoundError: the base class of the two above; nothing raises it
            directly.
        NoAgentsError: no configured name resolved to a target, so nothing was
            written. Nothing is written or backed up before this is raised.
        OSError: a target directory cannot be created, or a read or write fails
            (e.g. permissions, read-only filesystem, no space). A target whose
            backup fails is left alone rather than overwritten unprotected.
            Each target is replaced in a single step, so no individual file is
            left half-written, but the SET of targets is not all-or-nothing: a
            failure on the second target leaves the first already carrying the
            new rules. Re-running once the cause is fixed brings the rest into
            line.
        ValueError: the config file is not valid JSON.
        UnicodeDecodeError: a rules file is not valid UTF-8. A target that
            cannot be decoded cannot be backed up, so it is left alone too.
    """

    base = Path(base_dir)

    # Loaded once for the whole run. Three separate config_get calls re-read and
    # re-parsed the same file three times, and could disagree if it changed
    # underneath them mid-run.
    config   = Config.load()
    resolved = agent_targets(config.agents)

    # Writing zero files and returning normally reads as success at the exit
    # status, which is the failure this raise exists to make visible. Checked
    # before any file is touched so the run is all-or-nothing.
    if not resolved.targets:
        raise NoAgentsError(resolved.unknown)

    assembled = assembled_path()

    # One directory for the whole run, so every file this apply displaces lands
    # together rather than scattered across per-file timestamps.
    into = backup_dir(backup_stamp())

    # Supplied here rather than baked into the record, so a Config built by hand
    # still means "unset" rather than silently pointing somewhere.
    local_dir = config.local_rules_dir or default_local_rules_dir()

    # Discovered from the directory rather than from a list in this file, so a
    # module someone dropped in is picked up with no code change. Which of them
    # apply is then the config's business, and read_modules() raises rather than
    # skipping, so a module that was asked for cannot go missing quietly.
    discovered = discover_modules(base / RULES_DIRNAME)

    # Checked before anything is read, and against the config rather than
    # against the directory: with the directory globbed, a deleted module is
    # simply not discovered, so the config is the only place its absence is
    # still detectable.
    absent = missing_modules(discovered, config.modules)
    if absent:
        raise MissingModuleError(f"{absent[0]}.md", base / RULES_DIRNAME)

    shared_text = read_modules(selected_modules(discovered, config.modules))
    local_text  = read_local_rules(local_dir)

    # Every layer empty assembles to a document with no rules in it, which would
    # then replace every agent's live rules file. Refused before a single target
    # is opened, so those files are left as they are rather than blanked.
    if not shared_text.strip() and not local_text.strip():
        raise EmptyRulesError(base / RULES_DIRNAME)

    text    = assemble(shared_text, local_text)
    written = []

    # Written before the links so no agent path ever points at a file that is
    # not there yet, and written once because every agent reads the same text.
    _atomic_write(assembled, text)

    is_additive = config.rules_mode == RULES_MODE_ADDITIVE

    for target in resolved.targets:
        # Taken before either write, and deliberately allowed to raise: a file
        # whose contents could not be preserved is not replaced or appended to.
        # Additive mode keeps the file, but a backup is still the only way back
        # from a bad generated region.
        backup = _back_up(target.path, assembled, into)

        if is_additive:
            _append_to_target(target.path, text)
        else:
            _link_to_assembled(target.path, assembled)

        written.append(WrittenRules(agent=target.agent, target=target.path,
                                    backup=backup, is_appended=is_additive))

    return ApplyResult(written=written, unknown=resolved.unknown, assembled=assembled)
