import json
import os
from pathlib import Path

CONFIG_RELPATH = "ai-notes/config.json"
LOCAL_BEGIN    = "### LOCAL (DO NOT TOUCH — auto-generated by `ai-rules apply`) ###"
LOCAL_END      = "### END LOCAL ###"
NOTES_BEGIN    = "<!-- notes-nudge:start -->"
NOTES_END      = "<!-- notes-nudge:end -->"


def config_path():
    """Locate the machine-local config file.

    Honors $XDG_CONFIG_HOME, falling back to ~/.config. Does not create the
    file or its parent directory, and does not check that either exists.

    Args:
        None

    Returns:
        pathlib.Path: absolute path to the config file.

    Raises:
        None
    """
    # An empty XDG_CONFIG_HOME counts as unset, same as the XDG spec says
    base = os.environ.get("XDG_CONFIG_HOME")
    root = Path(base) if base else Path(os.path.expanduser("~")) / ".config"

    return root / CONFIG_RELPATH


def config_read():
    """Read the whole config file.

    Args:
        None

    Returns:
        dict: every setting in the file, or {} if the file does not exist.

    Raises:
        OSError: the file exists but cannot be read.
        ValueError: the file is not valid JSON.
    """
    path = config_path()
    if not path.is_file():
        return {}

    return json.loads(path.read_text(encoding="utf-8"))


def config_get(key, default=""):
    """Read one setting from the config file.

    Args:
        key (str): setting name to look up.
        default: returned when the key, or the config file itself, is absent.

    Returns:
        The stored value, with its JSON type preserved (str, bool, int, list,
        dict), or `default`.

    Raises:
        OSError: the config file exists but cannot be read.
        ValueError: the config file is not valid JSON.
    """
    return config_read().get(key, default)


def config_set(key, value):
    """Write one setting to the config file, creating it if needed.

    Args:
        key (str): setting name.
        value: any JSON-serializable value (str, bool, int, list, dict).

    Returns:
        None

    Raises:
        OSError: the parent directory cannot be created, or the write or the
            replace fails (e.g. permissions, read-only filesystem, no space).
        TypeError: `value` is not JSON-serializable.
        ValueError: the existing config file is not valid JSON.
    """
    data      = config_read()
    data[key] = value

    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    # Write to a scratch file and swap it in, so an interrupted write can never
    # leave a half-written config. The pid keeps concurrent writers apart.
    tmp = path.with_name("%s.%d.tmp" % (path.name, os.getpid()))
    try:
        tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        os.replace(str(tmp), str(path))
    finally:
        # A successful replace already moved the file, so this only fires when
        # the write failed partway.
        if tmp.exists():
            tmp.unlink()
